import type { Channel, Contact, Zone } from '../models';

export const sampleChannels: Channel[] = [
  {
    number: 1,
    name: 'Local Repeater',
    rxFrequency: 145.3500,
    txFrequency: 145.4500,
    mode: 'Analog',
    forbidTx: false,
    loneWorker: false,
    bandwidth: '25kHz',
    scanAdd: true,
    scanListId: 0,
    forbidTalkaround: false,
    unknown1A_6_4: 0,
    unknown1A_3: false,
    aprsReceive: false,
    emergencyIndicator: false,
    emergencyAck: false,
    emergencySystemId: 0,
    power: 'High',
    aprsReportMode: 'Off',
    unknown1C_1_0: 0,
    voxFunction: false,
    scramble: false,
    compander: false,
    talkback: false,
    unknown1D_3_0: 0,
    squelchLevel: 3,
    digitalEmergencySystemId: 0,
    pttIdDisplay: false,
    pttId: 0,
    colorCode: 0,
    rxCtcssDcs: { type: 'None' },
    txCtcssDcs: { type: 'CTCSS', value: 127.3 },
    companderDup: false,
    voxRelated: false,
    unknown25_7_6: 0,
    unknown25_3_0: 0,
    pttIdDisplay2: false,
    rxSquelchMode: 'Carrier/CTC',
    unknown26_3_1: 0,
    unknown26_0: false,
    stepFrequency: 5, // 25KHz
    signalingType: 'None',
    pttIdType: 'Off',
    unknown29_3_2: 0,
    unknown29_1_0: 0,
    unknown2A: 0,
    contactId: 0,
  },
  {
    number: 2,
    name: 'Simplex 146.52',
    rxFrequency: 146.5200,
    txFrequency: 146.5200,
    mode: 'Analog',
    forbidTx: false,
    loneWorker: false,
    bandwidth: '25kHz',
    scanAdd: true,
    scanListId: 0,
    forbidTalkaround: false,
    unknown1A_6_4: 0,
    unknown1A_3: false,
    aprsReceive: false,
    emergencyIndicator: false,
    emergencyAck: false,
    emergencySystemId: 0,
    power: 'High',
    aprsReportMode: 'Off',
    unknown1C_1_0: 0,
    voxFunction: false,
    scramble: false,
    compander: false,
    talkback: false,
    unknown1D_3_0: 0,
    squelchLevel: 3,
    digitalEmergencySystemId: 0,
    pttIdDisplay: false,
    pttId: 0,
    colorCode: 0,
    rxCtcssDcs: { type: 'None' },
    txCtcssDcs: { type: 'None' },
    companderDup: false,
    voxRelated: false,
    unknown25_7_6: 0,
    unknown25_3_0: 0,
    pttIdDisplay2: false,
    rxSquelchMode: 'Carrier/CTC',
    unknown26_3_1: 0,
    unknown26_0: false,
    stepFrequency: 5, // 25KHz
    signalingType: 'None',
    pttIdType: 'Off',
    unknown29_3_2: 0,
    unknown29_1_0: 0,
    unknown2A: 0,
    contactId: 0,
  },
  {
    number: 3,
    name: 'DMR Repeater',
    rxFrequency: 440.1250,
    txFrequency: 445.1250,
    mode: 'Digital',
    forbidTx: false,
    loneWorker: false,
    bandwidth: '12.5kHz',
    scanAdd: true,
    scanListId: 0,
    forbidTalkaround: false,
    unknown1A_6_4: 0,
    unknown1A_3: false,
    aprsReceive: false,
    emergencyIndicator: false,
    emergencyAck: false,
    emergencySystemId: 0,
    power: 'High',
    aprsReportMode: 'Off',
    unknown1C_1_0: 0,
    voxFunction: false,
    scramble: false,
    compander: false,
    talkback: false,
    unknown1D_3_0: 0,
    squelchLevel: 3,
    digitalEmergencySystemId: 0,
    pttIdDisplay: false,
    pttId: 0,
    colorCode: 1,
    rxCtcssDcs: { type: 'None' },
    txCtcssDcs: { type: 'None' },
    companderDup: false,
    voxRelated: false,
    unknown25_7_6: 0,
    unknown25_3_0: 0,
    pttIdDisplay2: false,
    rxSquelchMode: 'Carrier/CTC',
    unknown26_3_1: 0,
    unknown26_0: false,
    stepFrequency: 4, // 12.5KHz
    signalingType: 'None',
    pttIdType: 'Off',
    unknown29_3_2: 0,
    unknown29_1_0: 0,
    unknown2A: 0,
    contactId: 1,
  },
];

export const sampleContacts: Contact[] = [
  {
    id: 1,
    name: 'Local Repeater',
    dmrId: 1234567,
    callSign: 'KB4XYZ',
  },
  {
    id: 2,
    name: 'John Doe',
    dmrId: 7654321,
    callSign: 'KD4ABC',
  },
];

export const sampleZones: Zone[] = [
  {
    id: 'zone-sample-local',
    name: 'Local',
    channels: [1, 2],
  },
  {
    id: 'zone-sample-dmr',
    name: 'DMR',
    channels: [3],
  },
];

